include:
  - project: "renovate-bot/renovate-runner"
    file: "/templates/renovate.gitlab-ci.yml"

containers:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - echo "${CI_REGISTRY_PASSWORD}" | docker login "${CI_REGISTRY}" --username="${CI_REGISTRY_USER}" --password-stdin
  script:
    - CI_COMMIT_MESSAGE="${CI_COMMIT_MESSAGE//[$'\n']}"
    - NAME="${CI_COMMIT_MESSAGE%:*}"
    - VERSION="${CI_COMMIT_MESSAGE#*:}"
    - IMAGE="${CI_REGISTRY_IMAGE}/${NAME}"
    - TAG_VERSION="${IMAGE}:${VERSION}"
    - TAG_LATEST="${IMAGE}:latest"
    - docker build --pull --tag="${TAG_LATEST}" --tag="${TAG_VERSION}" --file "docker/containers/${NAME}/Dockerfile" "docker"
    - docker push --all-tags "${IMAGE}"
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
